# Generated by Django 2.2.6 on 2021-01-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210110_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bigthree',
            name='body_weight',
        ),
        migrations.RemoveField(
            model_name='bigthree',
            name='username',
        ),
    ]
