# Generated by Django 2.2.6 on 2021-01-31 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210124_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigthree',
            name='username',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
